src/FlaskRTBCTF/ctf/routes.py
""" views / routes. """


from datetime import datetime

from flask import Blueprint, render_template, flash, request, redirect, url_for
from flask_login import current_user, login_required
from FlaskRTBCTF.users.models import User, Logs
from FlaskRTBCTF.utils import (
    db,
    cache,
    is_past_running_time,
    admin_only,
    clear_points_cache,
    clear_rating_cache,
)
from .models import Machine, Category, UserChallenge, UserMachine
from .forms import (
    UserHashForm,
    RootHashForm,
    MachineForm,
    ChallengeFlagForm,
    RatingForm,
)


ctf = Blueprint("ctf", __name__)


# Scoreboard
@ctf.route("/scoreboard")
@cache.cached(timeout=120, key_prefix="scoreboard")
def scoreboard():
    usersScores = User.get_all()
    usersScores.sort(reverse=True, key=lambda user: user.points(id=user.id))

    return render_template("scoreboard.html", scores=usersScores)


# Machines Info
@ctf.route("/machines", methods=["GET", "POST"])
@login_required
def machines():
    userHashForm = UserHashForm()
    rootHashForm = RootHashForm()
    ratingForm = RatingForm()

    is_finished = is_past_running_time()

    if request.method == "GET":
        boxes = Machine.get_all()
        completed = UserMachine.completed_machines(user_id=current_user.id)
        rated = UserMachine.rated_machines(user_id=current_user.id)

        log = Logs.query.get(current_user.id)
        # check if it is the first visit to machine page for user
        if log.visitedMachine is False:
            log.visitedMachine = True
            log.machineVisitTime = datetime.utcnow()
            db.session.commit()

        return render_template(
            "machines.html",
            boxes=boxes,
            completed=completed,
            rated=rated,
            is_finished=is_finished,
            userHashForm=userHashForm,
            rootHashForm=rootHashForm,
            ratingForm=ratingForm,
        )

    else:
        if is_finished:
            flash("Sorry! CTF has ended.", "danger")
            return redirect(url_for("ctf.machines"))

        machine_id = int(userHashForm.machine_id.data or rootHashForm.machine_id.data)
        user_machine = UserMachine.query.filter_by(
            user_id=current_user.id, machine_id=machine_id
        ).first()

        if not user_machine:
            user_machine = UserMachine(user_id=current_user.id, machine_id=machine_id)
            db.session.add(user_machine)
            db.session.commit()

        if userHashForm.submit_user_hash.data and userHashForm.validate_on_submit():
            if user_machine.owned_user:
                flash("You already own User.", "success")
                return redirect(url_for("ctf.machines"))

            user_machine.owned_user = True
            log = Logs.query.get(current_user.id)
            log.userSubmissionIP = request.access_route[0]
            log.userSubmissionTime = datetime.utcnow()
            log.userOwnTime = str(log.userSubmissionTime - log.machineVisitTime)
            db.session.commit()
            clear_points_cache(userId=current_user.id, mode="m")
            flash("Congrats! correct user hash.", "success")

        elif rootHashForm.submit_root_hash.data and rootHashForm.validate_on_submit():
            if user_machine.owned_root:
                flash("You already own System.", "success")
                return redirect(url_for("ctf.machines"))

            user_machine.owned_root = True
            log = Logs.query.get(current_user.id)
            log.rootSubmissionIP = request.access_route[0]
            log.rootSubmissionTime = datetime.utcnow()
            log.rootOwnTime = str(log.rootSubmissionTime - log.machineVisitTime)
            db.session.commit()
            clear_points_cache(userId=current_user.id, mode="m")
            flash("Congrats! correct root hash.", "success")

        else:
            errors = userHashForm.user_hash.errors or rootHashForm.root_hash.errors
            for e in errors:
                flash(e, "danger")

        return redirect(url_for("ctf.machines"))


# New machine form
@ctf.route("/machines/new", methods=["GET", "POST"])
@admin_only
def new_machine():
    form = MachineForm(obj=Machine.query.get(1))
    if request.method == "GET":
        return render_template(
            "new_machine.html", form_title="Add New Machine", form=form
        )
    else:
        if form.validate_on_submit():
            new_machine = Machine()
            form.populate_obj(new_machine)
            db.session.add(new_machine)
            db.session.commit()
            cache.delete(key="machines")
            flash(f"{form.name.data} has been added.", "success")
            return redirect(url_for("ctf.machines"))
        else:
            flash(form.errors, "danger")
            return redirect(request.url)


# Edit machine form
@ctf.route("/machines/edit/<int:id>", methods=["GET", "POST"])
@admin_only
def edit_machine(id):
    machine = Machine.query.get_or_404(id)
    form = MachineForm(obj=machine)
    if request.method == "GET":
        return render_template(
            "new_machine.html", form_title=f"Editing machine #{id}", form=form
        )
    else:
        if form.validate_on_submit():
            form.populate_obj(machine)
            db.session.commit()
            cache.delete(key="machines")
            flash(f"{form.name.data} has been edited.", "success")
            return redirect(url_for("ctf.machines"))
        else:
            flash(form.errors, "danger")
            return redirect(request.url)


# Challenges Info
@ctf.route("/challenges", methods=["GET", "POST"])
@login_required
def challenges():
    flagForm = ChallengeFlagForm()
    ratingForm = RatingForm()

    if request.method == "GET":
        categories_challenges = Category.get_challenges()
        completed = UserChallenge.completed_challenges(user_id=current_user.id)
        rated = UserChallenge.rated_challenges(user_id=current_user.id)

        return render_template(
            "challenges.html",
            is_finished=is_past_running_time(),
            categories=categories_challenges,
            completed=completed,
            rated=rated,
            chalFlagForm=flagForm,
            chalRatingForm=ratingForm,
        )

    else:
        if is_past_running_time():
            flash("Sorry! CTF has ended.", "danger")

        elif flagForm.validate_on_submit():
            ch_id = int(flagForm.challenge_id.data)
            user_ch = UserChallenge.query.filter_by(
                user_id=current_user.id, challenge_id=ch_id
            ).first()

            if not user_ch:
                user_ch = UserChallenge(user_id=current_user.id, challenge_id=ch_id)
                db.session.add(user_ch)
            elif user_ch.completed:
                flash(
                    "You've already submitted the flag for this challenge.", "success"
                )
                return redirect(request.url)

            user_ch.completed = True
            db.session.commit()
            clear_points_cache(userId=current_user.id, mode="c")
            flash("Congrats! correct flag.", "success")

        else:
            flash(flagForm.errors, "danger")

        return redirect(url_for("ctf.challenges"))


# Rating Form Submit
@ctf.route("/submit_rating", methods=("POST",))
@login_required
def submit_rating():
    form = RatingForm()
    if form.validate_on_submit():
        if form.rating_for.data == "machine":
            try:
                user_machine = UserMachine.query.get(
                    {
                        "user_id": current_user.id,
                        "machine_id": form.machine_challenge_id.data,
                    }
                )
                if (
                    user_machine
                    and user_machine.owned_user
                    and user_machine.owned_root
                    and user_machine.rating == 0
                ):
                    user_machine.rating = form.rating_value.data
                    db.session.commit()
                    clear_rating_cache(
                        user_id=current_user.id, machine_id=user_machine.machine_id
                    )
                    flash("Thank you for rating!", "success")
                elif user_machine.rating != 0:
                    flash("You can only rate once", "danger")
                else:
                    flash(
                        "You can rate only after you own both System and User", "danger"
                    )
            except Exception as e:
                flash(str(e), "danger")

            return redirect(url_for("ctf.machines"))

        elif form.rating_for.data == "challenge":
            try:
                user_ch = UserChallenge.query.get(
                    {
                        "user_id": current_user.id,
                        "challenge_id": form.machine_challenge_id.data,
                    }
                )
                if user_ch.completed and user_ch.rating == 0:
                    user_ch.rating = form.rating_value.data
                    db.session.commit()
                    clear_rating_cache(
                        user_id=current_user.id, ch_id=user_ch.challenge_id
                    )
                    flash("Thank you for rating!", "success")
                elif user_ch.rating != 0:
                    flash("You can only rate once", "danger")
                elif not user_ch.completed:
                    flash("You can rate only after submitting flag", "danger")
            except Exception as e:
                flash(str(e), "danger")

            return redirect(url_for("ctf.challenges"))
    else:
        flash(form.errors, "danger")
        return redirect(url_for("main.home"))

src/FlaskRTBCTF/main/routes.py
from flask import render_template, Blueprint, redirect, url_for, request

from .models import Notification, Settings, Website
from .forms import SettingsForm, WebsiteForm
from FlaskRTBCTF.utils import admin_only

main = Blueprint("main", __name__)


""" Index page """


@main.route("/")
@main.route("/home")
def home():
    settings = Settings.get_settings()
    running_time = {
        "from": settings.running_time_from,
        "to": settings.running_time_to,
    }

    return render_template("home.html", RunningTime=running_time)


@main.route("/notifications")
def notifications():
    notifs = Notification.query.order_by(Notification.updated_on.desc()).all()

    return render_template("notifications.html", title="Notifications", notifs=notifs)


@main.route("/setup", methods=["GET", "POST"])
@admin_only
def setup():
    website_form_data = {"names": list(), "urls": list()}
    for w in Website.query.all():
        website_form_data["names"].append(w.name)
        website_form_data["urls"].append(w.url)

    settings_form_data = Settings.query.get(1)

    settings_form = SettingsForm(obj=settings_form_data)
    website_form = WebsiteForm(data=website_form_data)

    if request.method == "GET":
        return render_template(
            "setup.html",
            title="Setup",
            settingsForm=settings_form,
            websitesForm=website_form,
        )

    else:

        step = int(request.args.get("step", 2))

        if step == 2 and settings_form.validate_on_submit():
            return settings_form.setup()
        elif step == 3:
            return website_form.setup()
        else:
            return redirect(url_for("main.setup"))

src/FlaskRTBCTF/users/routes.py
from datetime import datetime
import pytz

from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required

from FlaskRTBCTF.utils import db, bcrypt, send_reset_email
from .forms import (
    RegistrationForm,
    LoginForm,
    RequestResetForm,
    ResetPasswordForm,
)
from .models import User, Logs


users = Blueprint("users", __name__)


""" User management """


@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        flash("Already Authenticated.", "info")
        return redirect(url_for("main.home"))

    form = RegistrationForm()

    if form.validate_on_submit():
        # hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
        #     "utf-8"
        # )
        user = User(
            username=form.username.data,
            email=form.email.data,
            password=form.password.data,
        )
        log = Logs(
            user=user,
            accountCreationTime=datetime.now(pytz.utc),
            visitedMachine=False,
            machineVisitTime=None,
            userSubmissionTime=None,
            rootSubmissionTime=None,
            userSubmissionIP=None,
            rootSubmissionIP=None,
        )

        db.session.add(log)
        db.session.add(user)
        db.session.commit()
        flash("Your account has been created! You are now able to log in.", "success")
        return redirect(url_for("users.login"))

    return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        flash("Already Authenticated", "info")
        return redirect(url_for("main.home"))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        pw_chk = bcrypt.check_password_hash(user.password, form.password.data)
        if user and pw_chk:
            login_user(user, remember=form.remember.data, force=True)
            next_page = request.args.get("next")
            return redirect(next_page) if next_page else redirect(url_for("main.home"))
        else:
            flash("Login Unsuccessful. Please check username and password.", "danger")
    return render_template("login.html", title="Login", form=form)


@users.route("/logout")
@login_required
def logout():
    logout_user()
    flash("Logged out.", "info")
    return redirect(url_for("main.home"))


@users.route("/account")
@login_required
def account():
    return render_template("account.html", title="Account")


@users.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RequestResetForm()
    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=form.email.data).first()
            send_reset_email(user)
            flash(
                "An email has been sent with instructions to reset your password.",
                "info",
            )
            return redirect(url_for("users.login"))
        except Exception:
            flash("Mail is not setup. Please contact admin directly.", "info")
            return redirect(request.url)
    return render_template("reset_request.html", title="Reset Password", form=form)


@users.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))

    user = User.verify_reset_token(token)

    if user is None:
        flash("That is an invalid or expired token", "danger")
        return redirect(url_for("users.reset_request"))

    form = ResetPasswordForm()

    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user.password = hashed_password
        db.session.commit()
        flash("Your password has been updated! You are now able to log in", "success")
        return redirect(url_for("users.login"))

    return render_template("reset_token.html", title="Reset Password", form=form)

src/FlaskRTBCTF/templates/account.html
{% extends "layout.html" %}


{% block content %}
 
    <div class="content-section">
        <h4>Username:</h4><span>{{ current_user.username }}</span>
        <hr/>
        <h4>Email:</h4>
        <span>{{ current_user.email }}</span>
    </div>

{% endblock content %}

src/FlaskRTBCTF/templates/forms.html
{% from 'macros.html' import form_field_group_macro %}

<!-- Login Form -->
{% macro login_form_macro(form, url) %}
<div class="content-section">
    <form method="POST" action="{{ url }}">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>
            <div class="form-group">
                {{ form_field_group_macro(field=form.username) }}
            </div>
            <div class="form-group">
                {{ form_field_group_macro(field=form.password) }}
            </div>
            <div class="custom-control custom-checkbox">
                {{ form.remember(class="custom-control-input") }}
                {{ form.remember.label(class="custom-control-label") }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-dark btn-hover-red") }}
        </div>
        <small>
            <a href="{{ url_for('users.reset_request') }}" class="red-underlined-link">Forgot Password?</a>
        </small>
    </form>
</div>

{% endmacro %}

<!-- Register Form -->
{% macro register_form_macro(form) %}
<div class="content-section">
    <form method="POST" action="{{ url_for('users.register') }}">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join Today</legend>
            <div class="form-group">
                {{ form_field_group_macro(field=form.username) }}
            </div>
            <div class="form-group">
                {{ form_field_group_macro(field=form.email) }}
            </div>
            <div class="form-group">
                {{ form_field_group_macro(field=form.password) }}
            </div>
            <div class="form-group">
                {{ form_field_group_macro(field=form.confirm_password) }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-dark btn-hover-red") }}
        </div>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-light">
        Already Have An Account? <a class="ml-2 red-underlined-link" href="{{ url_for('users.login') }}">Sign In</a>
    </small>
</div>
{% endmacro %}


<!-- Settings Form -->
{% macro settings_form_macro(form, url) %}
<div class="content-section">
    <form method="POST" action="{{ url }}">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">CTF Settings</legend>
            <div class="form-group">
                {{ form_field_group_macro(field=form.ctf_name) }}
            </div>
            <div class="form-group">
                {{ form_field_group_macro(field=form.organization_name) }}
            </div>

            <div class="form-control-label">Running Time</div>
            <code class="small">
                Date & Time should be in <b>UTC</b> Time Zone.
                <br>
                If you don't need to specify running time, make the end date's year far, far away in the future.
            </code>
            <div class="mt-3 d-flex form-group">
                {{ form_field_group_macro(field=form.from_date) }}
                {{ form_field_group_macro(field=form.from_time) }}
            </div>
            <div class="d-flex form-group">
                {{ form_field_group_macro(field=form.to_date) }}
                {{ form_field_group_macro(field=form.to_time) }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-dark btn-hover-red") }}
        </div>
    </form>
</div>

{% endmacro %}

<!-- Website Form -->
{% macro website_form_macro(form, url) %}
<div class="content-section">
    <form method="POST" action="{{ url }}">
        <fieldset class="d-flex align-items-center">
            <legend class="border-bottom mb-4">Add Websites for your organization</legend>
            <div class="form-group">
                {{ form.names.label(class="form-control-label") }}  
                {{ form.names(class="is-invalid", autocomplete="off") }}
            </div>
            <div class="form-group">
                {{ form.urls.label(class="form-control-label text-uppercase") }} 
                {{ form.urls(class="is-invalid", autocomplete="off")  }}
            </div>
        </fieldset>
        <div class="form-group">
            <a href="{{ url_for('main.setup', step=2) }}" class="mr-2 btn red-link">Go Back</a>
            {{ form.submit(class="btn btn-dark btn-hover-red") }}
        </div>
    </form>
</div>
{% endmacro %}


<!-- User Hash Form -->
{% macro user_hash_form_macro(form) %}

<form class="form-inline" method="POST" action="{{ url_for('ctf.machines') }}">
    {{ form.csrf_token() }}
    {{ form.machine_id(id="machine-id-user") }}
    <div class="form-group">
        {{ form.user_hash.label(class="form-control-label") }}
        {{ form.user_hash(
                class="ml-3 mr-3 is-invalid",
                size=24,
                minlength=32,
                maxlength=32,
                autocomplete="off"
            )
        }}
        {{ form.submit_user_hash(class="btn btn-sm btn-dark btn-hover-red") }}
    </div>
</form>

{% endmacro %}


<!-- Root Hash Form -->
{% macro root_hash_form_macro(form) %}

<form class="form-inline" method="POST" action="{{ url_for('ctf.machines') }}">
    {{ form.csrf_token() }}
    {{ form.machine_id(id="machine-id-root") }}
    <div class="form-group">
        {{ form.root_hash.label(class="form-control-label") }}
        {{ form.root_hash(
                class="ml-3 mr-3 is-invalid",
                size=24,
                minlength=32,
                maxlength=32,
                autocomplete="off"
            ) 
        }}
        {{ form.submit_root_hash(class="btn btn-sm btn-dark btn-hover-red") }}
    </div>
</form>

{% endmacro %}


<!-- User Hash Form -->
{% macro challenge_flag_submission_form(form) %}

<form class="form-inline" method="POST" action="{{ url_for('ctf.challenges') }}">
    {{ form.csrf_token() }}
    {{ form.challenge_id(id="challenge-id") }}
    <div class="form-group">
        {{ form.flag.label(class="form-control-label") }}
        {{ form.flag(
                class="ml-3 mr-3 is-invalid",
                size=28,
                minlength=4,
                autocomplete="off"
            )
        }}
        {{ form.submit_flag(class="btn btn-sm btn-dark btn-hover-red") }}
    </div>
</form>

{% endmacro %}

<!-- Rating Form -->
{% macro rating_submission_form(form) %}
  
<form class="form-inline" method="POST" action="{{ url_for('ctf.submit_rating') }}">
    {{ form.csrf_token() }}
    {{ form.machine_challenge_id(id="rating-id") }}
    {{ form.rating_for(id="rating-for") }}
    <div class="btn-group" role="group" aria-label="Rating">
        <input type="submit" name="rating_value" class="btn btn-dark btn-hover-red" value="1">
        <input type="submit" name="rating_value" class="btn btn-dark btn-hover-red" value="2">
        <input type="submit" name="rating_value" class="btn btn-dark btn-hover-red" value="3">
        <input type="submit" name="rating_value" class="btn btn-dark btn-hover-red" value="4">
        <input type="submit" name="rating_value" class="btn btn-dark btn-hover-red" value="5">
    </div>
</form>

{% endmacro %}

src/FlaskRTBCTF/templates/home.html
{% extends "layout.html" %}
{% block content %}

<div class="content-section">
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
            <h1 class="display-5">Welcome to {{ settings.ctf_name }}</h1>
            {% if current_user.is_authenticated %}
                <p class="lead">
                    Read the rules and have fun!
                </p>
            {% else %}
                <p class="lead">You need to <a class="red-underlined-link" href="{{ url_for('users.login') }}">login</a> first.</p>
            {% endif %}
      </div>
    </div>
</div>

<div class="content-section">
    <h2 class="title-heading">Rules</h2>
    <hr/>
    <ul>
        <li>Running time: 
            <code>{{ RunningTime['from'].strftime("%Y-%m-%d %I:%M %p") }}</code>
            to 
            <code>{{ RunningTime['to'].strftime("%Y-%m-%d %I:%M %p") }}</code>
             (All times in <code>UTC</code>)
        </li>
        <li>Needless to say: no bruteforcing (you'll never guess, anyway)</li>
        <li>Automated vulnerability scanners will get you nowhere.</li>
        <li>Attacking this CTF infrastructure website is unnecessary. There are no hints.</li>
        <li>Have fun! :)</li>
    </ul>
</div>

{% endblock content %}

src/FlaskRTBCTF/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- "Metadata. The story behind the data" ~ Elliot Alderson -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Favicon -->
  	<link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico')}}"/>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- Font Awesome -->
    <link rel="stylesheet" type="text/css"
          href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <!-- local css -->
    <link rel="stylesheet" type="text/css" 
          href="{{ url_for('static', filename='main.css') }}">
    <!-- Title --> 
    {% if title %}
        <title>{{ settings.ctf_name }} - {{ title }}</title>
    {% else %}
        <title>{{ settings.ctf_name }}</title>
    {% endif %}
</head>
<body>

    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">{{ settings.ctf_name }}</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.notifications') }}">Notifications</a>
              <a class="nav-item nav-link" href="{{ url_for('ctf.scoreboard') }}">Scoreboard</a>
              <a class="nav-item nav-link" href="{{ url_for('ctf.machines') }}">Machines</a>
              <a class="nav-item nav-link" href="{{ url_for('ctf.challenges') }}">Challenges</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                  {% if current_user.isAdmin %}
                    <a class="nav-item nav-link" href="/admin">Admin Controls</a>
                  {% endif %}
                  <a class="nav-item nav-link" href="{{ url_for('users.account') }}">@{{ current_user.username }}</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                {% else %}
                  <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                
                <div class="alert alert-{{ category }}">
                    {% if category == "danger" %}
                      <i class="fas fa-exclamation-triangle"></i>
                    {% elif category == "success" %}
                      <i class="far fa-check-circle"></i>
                    {% else %}
                      <i class="fas fa-info-circle"></i>
                    {% endif %}
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}

          <!-- All the main content goes here -->
          {% block content %}{% endblock %}

        </div>
        <div class="col-md-4">
            <div class="content-section">
              <h3>{{ settings.organization_name }}</h3>
              <p class="text-muted">
                <ul class="list-group">
                  {% for w in websites %}
                    <a target="_blank" 
                       href="{{ w.url }}" 
                       class="list-group-item list-group-item-action" 
                       rel="noreferrer noopener"
                    >
                      {{ w.name }}
                    </a>
                  {% endfor %}
                </ul>
              </p>
            </div>
        </div>
      </div>
    </main>

    <!-- jQuery and Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" 
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <!-- popper.js for popovers -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" 
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <!-- bootstrap.js -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" 
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <!-- main.js -->
    <script src="{{ url_for('static', filename='main.js') }}"></script>

</body>
</html>

src/FlaskRTBCTF/templates/login.html
{% extends "layout.html" %}
{% from "forms.html" import login_form_macro %}
{% block content %}
    
    {{ login_form_macro(form=form, url=url_for('users.login') ) }}
    <div class="border-top pt-3">
        <small class="text-light">
            Need An Account? <a class="ml-2 red-underlined-link" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
    
{% endblock content %}

src/FlaskRTBCTF/templates/notifications.html
{% extends "layout.html" %}
{% block content %}

{% if current_user.isAdmin %}
    <a href="/admin/notification/new/" class="ml-2 red-underlined-link">Add new</a>
{% endif %}
<div class="content-section">
    {% for notif in notifs %}
        <div class="content-section">
            <h3 class="title-heading">{{ notif['title'] }}</h3>
            <div class="float-right">
            <small>Notification #{{ notif['id'] }} - posted at <code>{{ notif['updated_on'].strftime("%Y-%m-%d %I:%M %p %Z") }}</code></small>
            </div><br/>
            <hr/>
            <p>{{ notif['body'] }}</p>
        </div>
    {% endfor %}
</div>

{% endblock content %}

src/FlaskRTBCTF/templates/register.html
{% extends "layout.html" %}
{% from "forms.html" import register_form_macro %}

{% block content %}

    {{ register_form_macro(form) }}

{% endblock content %}